### ISSUE TITLE
[UMBRELLA] CNCF Sandbox project onboarding 

### ISSUE THREAD

**Issue by maxgio92** [projectcapsule/capsule#812]
**General**

This is an umbrella issue to track the status of all the required points that need to be addressed in the Git repository and GitHub:

- [x] Review and expand the open governance. See [CNCF governance](https://contribute.cncf.io/maintainers/governance/) - cncf/toc#901 
- [x] Move the GitHub repository in its own separate neutral GitHub organization (ensure 'thelinuxfoundation' and 'caniszczyk' are added as initial org owners)
- [ ] Move documentation to MkDocs - cncf/toc#821 
- [x] Ensure [DCO](https://github.com/apps/dco) or [CLA](https://github.com/cncf/cla) are enabled for all GitHub repositories of the project
- [x] Ensure that hat the [CNCF Code of Conduct](https://github.com/cncf/foundation/blob/master/code-of-conduct.md) (or your adopted version of it) are explicitly referenced at the project's README on GitHub
- [x] CII: Start on a CII best practices badge https://bestpractices.coreinfrastructure.org/en
- [x] Adopt a license scanning tool, like [FOSSA](https://fossa.com/) or [Snyk](https://snyk.io/)

**Additional informations**

Related to: https://github.com/cncf/sandbox/issues/166

**Comment by prometherion** [comment]
License scanning has been introduced with #810 by @ptx96

**Comment by prometherion** [comment]
CII has been addressed with #816.

**Comment by prometherion** [comment]
Adhering to CNCF ToC is addressed with #817.

**Comment by oliverbaehler** [comment]
@prometherion @maxgio92 @MaxFedotov  Do we also need to create a new organisation on artifacthub? I would like to start with trivial stuff in the CLO Monitor like Artifacthub Badges etc. Should I create an organisation and add all the maintiners?

**Comment by prometherion** [comment]
It makes definitely sense.

I just created the organization on Artifact Hub, please, share your usernames (publicly, or privately) so I can add you there: thanks for the heads up, @oliverbaehler! ❤️

**Comment by MaxFedotov** [comment]
> It makes definitely sense.
> 
> I just created the organization on Artifact Hub, please, share your usernames (publicly, or privately) so I can add you there: thanks for the heads up, @oliverbaehler! ❤️

Hey! Mine is the same as here, MaxFedotov

**Comment by oliverbaehler** [comment]
@prometherion should we still make changes against the current capsule repostories or should we qait until its moved to the new organisation?

Mine is also oliverbaehler, thanks.

I will start working on a draft for a new release path, including sboms etc to satisfy clo

**Comment by prometherion** [comment]
The new organization has been created, and Chris Aniszczyk from CNCF accepted the invitation.

I would move the project once any reference from the documentation is pointing to the new organization: does it make sense, @oliverbaehler?

I never moved a repository hosting a Go module, wondering if this will break all the third-party dependencies too, such as `capsule-proxy`, or any other project using github.com/clastix/capsule.

**Comment by oliverbaehler** [comment]
Onboarding has been completed
